# Site settings
title: Hi, I'm James
description: Wort wort wort 
url: "https://j-leg.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm James 
user_description: fascinated by things "aggressively" simple
email: jamesz96.au@gmail.com
twitter_username: lorem_ipsum
github_username: J-leg 
gplus_username:  lorem_ipsum

# Animated favicons will only be visible on Firefox AFAIK
favicon: animated_favicon.gif

small_asides:
  - title: tracula
    desc: Small game population (serverless) tracker written in Go
    link: https://github.com/J-Leg/tracula
  - title: players.fyi
    desc: Next.js front-end component of tracula
    link: https://players.fyi/ 
  - title: clue-bot 
    desc: Node.js Reddit bot that simulates an in-game live pricing/reward system
    link: https://github.com/J-Leg/clue-bot
  - title: Audio-Mango
    desc: Lightweight Python utility for audio steganography
    link: https://github.com/J-Leg/Audio-Mango
  - title: particulate
    desc: This portfolio page
    link: https://github.com/J-Leg/particulate

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
